### ISSUE TITLE
API / 422 - Unprocessable Entity

### ISSUE THREAD

**Issue by inviqus** [evo-doc/backend#13]
Nová globální kontrola. Dřív se kvůli nedostatku dat vracela 400 (nikde nebylo specifikováno).

Ted, pokud budou chybět potřebná data nebo budou jiného typu (tzn. úplně chybí password, password je array), tak se bude vracet `422 Unprocessable Entity`:

```json
{
	"message": "Not enough data to process the request."
}
```

Specifikovat, co přesně chybí, není potřeba.

V případě existence proměnné a validního typu, ale nevalidní hodnoty (tzn. prázdný login) se vrací `400 Bad Request` s udáním poškozené proměnné:

```json
{
    "message": "Some data are invalid.",
    "invalid": ["variable_name"]
}
```

Konkrétní typy a názvy se vážou na konkrétní API requesty, viz postman.

**Comment by DanHampl** [comment]
@inviqus please add to the postman

**Comment by inviqus** [comment]
@DanHampl Done

**Comment by DanHampl** [comment]
resolved in #15

**Comment by inviqus** [comment]
In case of a missing token (`Authorized` header) server also needs to send `422` error (of course only if the request needs a token).

**Comment by inviqus** [comment]
`401` is OK
