### ISSUE TITLE
Problém s testy

### ISSUE THREAD

**Issue by TomStary** [evo-doc/backend#28]
Při vícenásobném spuštění integračních testů, testy neprojdou, neboť se nedropne v databáze. Problém je někde v `tests/conftest.py`.

**Comment by MarekSuchanek** [comment]
Zkusil jsem trochu pogooglit a tohle pomohlo

```python
    with app.app_context():
        app.db.reflect()
        app.db.drop_all()
```

http://jrheard.tumblr.com/post/12759432733/dropping-all-tables-on-postgres-using

**Comment by TomStary** [comment]
Děkuji, closing
