### ISSUE TITLE
Project api

### ISSUE THREAD

**Issue by DanHampl** [evo-doc/backend#34]
- [x] create project
- [x] view project
- [x] update project
- [x] rm project
- [x] add contributor
- [x] rm contributor

**Comment by TomStary** [comment]
BUG: When adding project, I do get 422 error while no data has been sent, but I don't get any information which values are missing.

**Comment by TomStary** [comment]
We have to address issue with required data in api request too.

**Comment by DanHampl** [comment]
uz sis to resolvnul nebo to ma nak resit? @TomStary

**Comment by TomStary** [comment]
Asi dobrý

**Comment by TomStary** [comment]
rm dělej zatím soft delete

**Comment by DanHampl** [comment]
#38
