### ISSUE TITLE
authentication

### ISSUE THREAD

**Issue by DanHampl** [evo-doc/backend#5]
- [x] password @TomStary 
- [x] token @DanHampl 
- [x] signIn @DanHampl 
- [x] signOut @DanHampl 
- [x] signUp @DanHampl 
- [x] activate user @DanHampl

**Comment by DanHampl** [comment]
#7 still need your magic dream password

**Comment by TomStary** [comment]
Done, bcrypt je v appu (`app.bcrypt`)
